openapi: 3.0.0
info:
  title: Ketamine AI Admin API
  version: 1.0.0
  description: API for admin panel functionality

paths:
  /api/admin/documents:
    get:
      summary: Get list of all uploaded documents with their status
      operationId: getDocuments
      security:
        - apiKey: []
      responses:
        '200':
          description: List of documents with their training status
          content:
            application/json:
              schema:
                type: object
                properties:
                  documents:
                    type: array
                    items:
                      $ref: '#/components/schemas/KnowledgeDoc'
        '401':
          description: Unauthorized - API key required
        '500':
          description: Internal server error

  /api/admin/logs:
    get:
      summary: Get audit logs of document uploads
      operationId: getAuditLogs
      security:
        - apiKey: []
      parameters:
        - name: limit
          in: query
          required: false
          schema:
            type: integer
            default: 50
        - name: offset
          in: query
          required: false
          schema:
            type: integer
            default: 0
      responses:
        '200':
          description: Audit log entries
          content:
            application/json:
              schema:
                type: object
                properties:
                  logs:
                    type: array
                    items:
                      $ref: '#/components/schemas/AuditLog'
                  total:
                    type: integer
        '401':
          description: Unauthorized - API key required
        '500':
          description: Internal server error

components:
  securitySchemes:
    apiKey:
      type: apiKey
      in: header
      name: X-API-Key
  schemas:
    KnowledgeDoc:
      type: object
      properties:
        id:
          type: string
          example: "doc_12345"
        filename:
          type: string
          example: "ketamine-study.pdf"
        isKetamineRelevant:
          type: boolean
          example: true
        uploadedAt:
          type: string
          format: date-time
          example: "2026-01-15T10:30:00Z"
        uploaderId:
          type: string
          example: "admin_user"
        status:
          type: string
          enum: [processing, training, non-training, failed]
          example: "training"

    AuditLog:
      type: object
      properties:
        id:
          type: string
          example: "log_67890"
        userId:
          type: string
          example: "admin_user"
        action:
          type: string
          example: "upload_document"
        resource:
          type: string
          example: "ketamine-study.pdf"
        timestamp:
          type: string
          format: date-time
          example: "2026-01-15T10:30:00Z"
        details:
          type: object
          additionalProperties: true